### ISSUE TITLE
ToDo für ersten Test

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_UrbanOps.Altis#1]
- [x] Spielende, wenn Dealer tot und Opfor Spieler tot + Stadt unter Blufor Kontrolle
- [x] Spielende, wenn Commandvehicle zerstört und Blufor tot
- [x] Spielende, wenn Opfor die Stadt x (Parameter) Sekunden gehalten hat
- [x] Blufor Respawn abbrechen, wenn Commandvehicle zerstört wird
- [x] Opfor Respawn abbrechen, wenn Dealer getötet wird
- [x] Opfor Respawn Mindestabstand zu Bluforeinheiten
- [x] nicht-statische Zivilisten
- [x] Dealermarker
