### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_UrbanOps.Altis#10]
- [x] Kaufmenü: Sprengladungen
- [x] für andere Inseln konfigurieren
- [x] Kaufmenü: zweites Commandvehicle
- [x] Respawn nicht möglich, wenn Gegner in der Nähe (hint?)
- [x] Kaufmenü: Granaten (HE, Smoke)
- [x] permission level setzen
- [x] Geld verteilen
- [x] alle `openMap [true,false]` auf `[true,true]` setzen
