### ISSUE TITLE
ToDo 2

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_UrbanOps.Altis#8]
- [x] Loadouts US, RUS
- [x] evtl. Itemamount aus Itemdata auslagern, damit PV kleiner?
- [ ] Strafe Blufor bei Civkill
- [ ] Strafe Opfor bei Civkill
- [ ] Kaufmenü Itemconfig
- [ ] Geldparameter
- [ ] Engima Traffic
- [ ] JIP (money action)

**Comment by McDiod** [comment]
CIVSKILLEDBLU
CIVSKILLEDOPF

**Comment by McDiod** [comment]
Server:
```
while {spiel läuft} do {
  startzeit = time;
  waitUntil {sleep 5; time - startzeit > eventintervall};
  [] spawn serverevent;
};
```

```
serverevent = {
  maxrandom = abhängig von civskilleddifference;
  randomzahl = random maxrandom;
  switch (randomzahl) do {
    0-10: marker auf feindlichen einheiten
    11-20: marker auf dealer/commandvehicle
    21-30: zivilisten nehmen waffen in die hand
  };

  markerpositionsarray bestimmen;
  [seite, eventtyp, markerpositionsarray] remoteExec [clientevent, 0, false];
};
```

Client:

```
clientevent = {
  if (seite != eventseite) exitWith {};
  marker lokal erstellen;
  [] spawn {
    for 0 bis 10 schritt 1
    {
      allemarker markersetalphalocal (derzeitigesalpha - 0.1);
      sleep 15;
    };
  };
};
```
